### ISSUE TITLE
Request for Autoencoder Training Script for Compression and Reconstruction Network Using Frozen BART Base

### ISSUE THREAD

**Issue by RaswanthMurugan20** [justinlovelace/latent-diffusion-for-language#12]
Hi @justinlovelace,

I found the LD4GG paper V2 to be excellent and am interested in applying its concepts to my own work. The paper is well-written and clearly presents its ideas. 

I am currently attempting to replicate the described methods and seek assistance with training the compression and reconstruction network using a frozen BART base. Could you share the training script for the Autoencoder (to get an idea on how it was done if it isn't the whole pipeline)? If it's not feasible to upload it publicly at this moment, I would be willing to receive it via email. I'll reach out to you using the contact information provided in the paper if you prefer that.

**Comment by justinlovelace** [comment]
Hello,

Thank you for your interest in our work! We have updated the repo with the code corresponding to the updated preprint. See `script/autoencoder/` for a reference training script using the frozen BART base model. Feel free to reopen the issue if you have any questions.
