### ISSUE TITLE
Time cost for training and inference

### ISSUE THREAD

**Issue by dhx20150812** [justinlovelace/latent-diffusion-for-language#5]
Hi,

Very nice work!

In the paper, you have noticed that your whole models were trained on either a single Nvidia A6000 or a single Nvidia 3090. But I'm still curious about the actual time cost (e.g. how many hours does it take to train your class-conditional diffusion model for the AG News datasets in a single Nvidia 3090)

**Comment by justinlovelace** [comment]
Thank you for your interest! 

We report the wall-clock time for training all of the models in Table 10 in the appendix. All of the numbers are from training on a single Nvidia A6000 GPU. We also report inference time across a variety of sampling configurations in Table 6 in the appendix. If you have any additional questions then feel free to re-open the issue.

**Comment by dhx20150812** [comment]
Got it. Thanks for your reply.

Sorry for my negligence.
